"""Communication webapp templates."""

from webapps.templates.registry import WebAppTemplate

COMMUNICATION_TEMPLATES = [
    WebAppTemplate(
        template_id="whatsapp",
        name="WhatsApp",
        url="https://web.whatsapp.com",
        icon="whatsapp",
        category="Network",
        comment="Messaging and calls from WhatsApp",
        generic_name="Instant Messaging",
        keywords=("whatsapp", "chat", "messaging", "calls"),
        features=("notifications", "camera", "microphone"),
    ),
    WebAppTemplate(
        template_id="telegram",
        name="Telegram",
        url="https://web.telegram.org",
        icon="telegram",
        category="Network",
        comment="Fast and secure messaging from Telegram",
        generic_name="Instant Messaging",
        keywords=("telegram", "chat", "messaging", "channels"),
        features=("notifications",),
        url_schemes=("tg",),
    ),
    WebAppTemplate(
        template_id="discord",
        name="Discord",
        url="https://discord.com/app",
        icon="discord",
        category="Network",
        comment="Voice, video and text communication",
        generic_name="Instant Messaging",
        keywords=("discord", "chat", "voice", "gaming", "community"),
        features=("notifications", "camera", "microphone"),
    ),
    WebAppTemplate(
        template_id="slack",
        name="Slack",
        url="https://app.slack.com",
        icon="slack",
        category="Network",
        comment="Team communication and collaboration",
        generic_name="Instant Messaging",
        keywords=("slack", "chat", "team", "work", "collaboration"),
        features=("notifications", "camera", "microphone"),
    ),
    WebAppTemplate(
        template_id="messenger",
        name="Messenger",
        url="https://www.messenger.com",
        icon="messenger",
        category="Network",
        comment="Messaging from Facebook Messenger",
        generic_name="Instant Messaging",
        keywords=("messenger", "facebook", "chat", "messaging"),
        features=("notifications", "camera", "microphone"),
    ),
    WebAppTemplate(
        template_id="skype",
        name="Skype",
        url="https://web.skype.com",
        icon="skype",
        category="Network",
        comment="Video calls and messaging from Skype",
        generic_name="Video Conferencing",
        keywords=("skype", "video", "calls", "chat", "microsoft"),
        features=("notifications", "camera", "microphone"),
    ),
    WebAppTemplate(
        template_id="signal",
        name="Signal",
        url="https://signal.org/",
        icon="signal",
        category="Network",
        comment="Private messaging from Signal",
        generic_name="Instant Messaging",
        keywords=("signal", "privacy", "messaging", "encrypted"),
        features=("notifications",),
    ),
]
