"""Google Workspace webapp templates."""

from webapps.templates.registry import WebAppTemplate

GOOGLE_TEMPLATES = [
    WebAppTemplate(
        template_id="google-docs",
        name="Google Docs",
        url="https://docs.google.com",
        icon="google-docs",
        category="Office",
        comment="Create and edit documents online",
        generic_name="Word Processor",
        keywords=("google", "docs", "document", "text"),
        mime_types=(
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/msword",
            "application/rtf",
            "text/plain",
        ),
        file_handler="upload",
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-sheets",
        name="Google Sheets",
        url="https://sheets.google.com",
        icon="google-sheets",
        category="Office",
        comment="Create and edit spreadsheets online",
        generic_name="Spreadsheet",
        keywords=("google", "sheets", "spreadsheet", "csv", "excel"),
        mime_types=(
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-excel",
            "text/csv",
        ),
        file_handler="upload",
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-slides",
        name="Google Slides",
        url="https://slides.google.com",
        icon="google-slides",
        category="Office",
        comment="Create and edit presentations online",
        generic_name="Presentation",
        keywords=("google", "slides", "presentation", "powerpoint"),
        mime_types=(
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "application/vnd.ms-powerpoint",
        ),
        file_handler="upload",
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-drive",
        name="Google Drive",
        url="https://drive.google.com",
        icon="google-drive",
        category="Network",
        comment="Cloud storage from Google Drive",
        generic_name="Cloud Storage",
        keywords=("google", "drive", "cloud", "storage", "files"),
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-gmail",
        name="Gmail",
        url="https://mail.google.com",
        icon="gmail",
        category="Network",
        comment="Email from Google",
        generic_name="Email Client",
        keywords=("gmail", "email", "mail", "google"),
        features=("notifications",),
        url_schemes=("mailto",),
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-calendar",
        name="Google Calendar",
        url="https://calendar.google.com",
        icon="google-calendar",
        category="Office",
        comment="Calendar and scheduling from Google",
        generic_name="Calendar",
        keywords=("google", "calendar", "schedule", "events"),
        features=("notifications",),
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-meet",
        name="Google Meet",
        url="https://meet.google.com",
        icon="google-meet",
        category="Network",
        comment="Video conferencing from Google",
        generic_name="Video Conferencing",
        keywords=("google", "meet", "video", "conferencing"),
        features=("notifications", "camera", "microphone"),
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-photos",
        name="Google Photos",
        url="https://photos.google.com",
        icon="google-photos",
        category="Graphics",
        comment="Photo storage and editing from Google",
        generic_name="Photo Manager",
        keywords=("google", "photos", "gallery", "images"),
        profile="google",
    ),
    WebAppTemplate(
        template_id="google-keep",
        name="Google Keep",
        url="https://keep.google.com",
        icon="google-keep",
        category="Office",
        comment="Notes and lists from Google",
        generic_name="Note Taking",
        keywords=("google", "keep", "notes", "lists", "todo"),
        profile="google",
    ),
    WebAppTemplate(
        template_id="youtube",
        name="YouTube",
        url="https://www.youtube.com",
        icon="youtube",
        category="AudioVideo",
        comment="Watch and share videos",
        generic_name="Video Player",
        keywords=("youtube", "video", "streaming", "google"),
        features=("notifications",),
        profile="google",
    ),
]
