"""Media & entertainment webapp templates."""

from webapps.templates.registry import WebAppTemplate

MEDIA_TEMPLATES = [
    WebAppTemplate(
        template_id="spotify",
        name="Spotify",
        url="https://open.spotify.com",
        icon="spotify",
        category="AudioVideo",
        comment="Music streaming from Spotify",
        generic_name="Music Player",
        keywords=("spotify", "music", "streaming", "audio", "playlist"),
        features=("notifications", "media-keys"),
        url_schemes=("spotify",),
    ),
    WebAppTemplate(
        template_id="youtube-music",
        name="YouTube Music",
        url="https://music.youtube.com",
        icon="youtube-music",
        category="AudioVideo",
        comment="Music streaming from YouTube Music",
        generic_name="Music Player",
        keywords=("youtube", "music", "streaming", "google"),
        features=("notifications", "media-keys"),
        profile="google",
    ),
    WebAppTemplate(
        template_id="netflix",
        name="Netflix",
        url="https://www.netflix.com",
        icon="netflix",
        category="AudioVideo",
        comment="Watch movies and TV shows on Netflix",
        generic_name="Video Player",
        keywords=("netflix", "streaming", "movies", "series"),
    ),
    WebAppTemplate(
        template_id="prime-video",
        name="Amazon Prime Video",
        url="https://www.primevideo.com",
        icon="prime-video",
        category="AudioVideo",
        comment="Watch movies and TV shows on Prime Video",
        generic_name="Video Player",
        keywords=("amazon", "prime", "video", "streaming", "movies"),
    ),
    WebAppTemplate(
        template_id="disney-plus",
        name="Disney+",
        url="https://www.disneyplus.com",
        icon="disney-plus",
        category="AudioVideo",
        comment="Watch Disney, Marvel, Star Wars and more",
        generic_name="Video Player",
        keywords=("disney", "streaming", "movies", "marvel", "star wars"),
    ),
    WebAppTemplate(
        template_id="tidal",
        name="Tidal",
        url="https://listen.tidal.com",
        icon="tidal",
        category="AudioVideo",
        comment="HiFi music streaming from Tidal",
        generic_name="Music Player",
        keywords=("tidal", "music", "hifi", "streaming", "lossless"),
        features=("media-keys",),
    ),
    WebAppTemplate(
        template_id="deezer",
        name="Deezer",
        url="https://www.deezer.com",
        icon="deezer",
        category="AudioVideo",
        comment="Music streaming from Deezer",
        generic_name="Music Player",
        keywords=("deezer", "music", "streaming"),
        features=("media-keys",),
    ),
    WebAppTemplate(
        template_id="twitch",
        name="Twitch",
        url="https://www.twitch.tv",
        icon="twitch",
        category="AudioVideo",
        comment="Live streaming platform",
        generic_name="Streaming",
        keywords=("twitch", "streaming", "gaming", "live"),
        features=("notifications",),
    ),
]
