"""Microsoft Office 365 webapp templates."""

from webapps.templates.registry import WebAppTemplate

OFFICE365_TEMPLATES = [
    WebAppTemplate(
        template_id="office365-word",
        name="Microsoft Word",
        url="https://www.office.com/launch/word",
        icon="ms-word",
        category="Office",
        comment="Edit documents online with Microsoft Word",
        generic_name="Word Processor",
        keywords=("word", "document", "office", "docx", "microsoft"),
        mime_types=(
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/msword",
            "application/rtf",
            "text/rtf",
        ),
        file_handler="upload",
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-excel",
        name="Microsoft Excel",
        url="https://www.office.com/launch/excel",
        icon="ms-excel",
        category="Office",
        comment="Edit spreadsheets online with Microsoft Excel",
        generic_name="Spreadsheet",
        keywords=("excel", "spreadsheet", "office", "xlsx", "csv", "microsoft"),
        mime_types=(
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-excel",
            "text/csv",
            "application/csv",
        ),
        file_handler="upload",
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-powerpoint",
        name="Microsoft PowerPoint",
        url="https://www.office.com/launch/powerpoint",
        icon="ms-powerpoint",
        category="Office",
        comment="Create presentations online with Microsoft PowerPoint",
        generic_name="Presentation",
        keywords=("powerpoint", "presentation", "office", "pptx", "slides", "microsoft"),
        mime_types=(
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "application/vnd.ms-powerpoint",
        ),
        file_handler="upload",
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-onenote",
        name="Microsoft OneNote",
        url="https://www.onenote.com/notebooks",
        icon="ms-onenote",
        category="Office",
        comment="Take notes online with Microsoft OneNote",
        generic_name="Note Taking",
        keywords=("onenote", "notes", "office", "microsoft"),
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-outlook",
        name="Microsoft Outlook",
        url="https://outlook.live.com/mail/",
        icon="ms-outlook",
        category="Office",
        comment="Email and calendar from Microsoft Outlook",
        generic_name="Email Client",
        keywords=("outlook", "email", "mail", "calendar", "microsoft"),
        features=("notifications",),
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-teams",
        name="Microsoft Teams",
        url="https://teams.microsoft.com",
        icon="ms-teams",
        category="Network",
        comment="Chat and video conferencing with Microsoft Teams",
        generic_name="Instant Messaging",
        keywords=("teams", "chat", "video", "conferencing", "microsoft"),
        features=("notifications", "camera", "microphone"),
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-onedrive",
        name="Microsoft OneDrive",
        url="https://onedrive.live.com",
        icon="onedrive",
        category="Network",
        comment="Cloud storage from Microsoft OneDrive",
        generic_name="Cloud Storage",
        keywords=("onedrive", "cloud", "storage", "files", "microsoft"),
        profile="office365",
    ),
    WebAppTemplate(
        template_id="office365-home",
        name="Microsoft 365",
        url="https://www.office.com",
        icon="ms-office",
        category="Office",
        comment="Microsoft 365 home — access all Office apps",
        generic_name="Office Suite",
        keywords=("office", "365", "microsoft", "word", "excel", "powerpoint"),
        profile="office365",
    ),
]
