"""Productivity webapp templates."""

from webapps.templates.registry import WebAppTemplate

PRODUCTIVITY_TEMPLATES = [
    WebAppTemplate(
        template_id="notion",
        name="Notion",
        url="https://www.notion.so",
        icon="notion",
        category="Office",
        comment="All-in-one workspace for notes, docs, and projects",
        generic_name="Project Management",
        keywords=("notion", "notes", "docs", "wiki", "project", "management"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="todoist",
        name="Todoist",
        url="https://todoist.com/app",
        icon="todoist",
        category="Office",
        comment="Task management and to-do lists",
        generic_name="Task Manager",
        keywords=("todoist", "tasks", "todo", "productivity"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="trello",
        name="Trello",
        url="https://trello.com",
        icon="trello",
        category="Office",
        comment="Visual project management with boards and cards",
        generic_name="Project Management",
        keywords=("trello", "kanban", "boards", "project", "management"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="figma",
        name="Figma",
        url="https://www.figma.com",
        icon="figma",
        category="Graphics",
        comment="Collaborative design tool",
        generic_name="Design Tool",
        keywords=("figma", "design", "ui", "ux", "prototype", "vector"),
    ),
    WebAppTemplate(
        template_id="canva",
        name="Canva",
        url="https://www.canva.com",
        icon="canva",
        category="Graphics",
        comment="Online graphic design tool",
        generic_name="Design Tool",
        keywords=("canva", "design", "graphics", "templates", "poster"),
    ),
    WebAppTemplate(
        template_id="github",
        name="GitHub",
        url="https://github.com",
        icon="github",
        category="Development",
        comment="Code hosting and collaboration platform",
        generic_name="Code Hosting",
        keywords=("github", "git", "code", "repository", "development"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="gitlab",
        name="GitLab",
        url="https://gitlab.com",
        icon="gitlab",
        category="Development",
        comment="DevOps platform for software development",
        generic_name="DevOps Platform",
        keywords=("gitlab", "git", "devops", "ci", "cd", "development"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="chatgpt",
        name="ChatGPT",
        url="https://chatgpt.com",
        icon="chatgpt",
        category="Utility",
        comment="AI assistant from OpenAI",
        generic_name="AI Assistant",
        keywords=("chatgpt", "ai", "openai", "assistant", "gpt"),
    ),
    WebAppTemplate(
        template_id="claude",
        name="Claude",
        url="https://claude.ai",
        icon="claude",
        category="Utility",
        comment="AI assistant from Anthropic",
        generic_name="AI Assistant",
        keywords=("claude", "ai", "anthropic", "assistant"),
    ),
    WebAppTemplate(
        template_id="linkedin",
        name="LinkedIn",
        url="https://www.linkedin.com",
        icon="linkedin",
        category="Network",
        comment="Professional networking platform",
        generic_name="Social Network",
        keywords=("linkedin", "professional", "networking", "jobs"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="twitter",
        name="X (Twitter)",
        url="https://x.com",
        icon="twitter",
        category="Network",
        comment="Social media and news platform",
        generic_name="Social Network",
        keywords=("twitter", "x", "social", "news", "microblog"),
        features=("notifications",),
    ),
    WebAppTemplate(
        template_id="reddit",
        name="Reddit",
        url="https://www.reddit.com",
        icon="reddit",
        category="Network",
        comment="Community discussion and content sharing",
        generic_name="Social Network",
        keywords=("reddit", "community", "forum", "discussion"),
        features=("notifications",),
    ),
]
