[package]
publish = false  # internal workspace crate; not for crates.io
name = "webapps-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "big-webapps-exec"
path = "src/main.rs"

[dependencies]
webapps-core = { path = "../webapps-core" }
big-os-kit = { path = "../../../big-rust-components/crates/big-os-kit" }
libc = "0.2"
