// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1585246999);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1585247029);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 11163);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1585246930);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{980baa16-9111-4134-a368-558e432267aa}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1585247032343");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1585248827343");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1585246937255");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1585250537255");
user_pref("browser.search.region", "BR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1585246970");
user_pref("browser.slowStartup.averageTime", 3942);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200309095159");
user_pref("browser.startup.homepage_override.mstone", "74.0");
user_pref("browser.startup.lastColdStartupCheck", 1585246970);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1585246934671");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "74.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "f61f1bde1e94475d93c72e50f7087553");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200309095159");
user_pref("extensions.lastAppVersion", "74.0");
user_pref("extensions.lastPlatformVersion", "74.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c5f334f6-9a49-4f42-b2b7-474de7017b52\",\"formautofill@mozilla.org\":\"d7ac016c-3f61-4639-b23e-308c2e72c1b0\",\"screenshots@mozilla.org\":\"3ad7cece-9494-492d-a4b2-1d8884a15148\",\"webcompat-reporter@mozilla.org\":\"e8dea6d8-4ca9-48bb-8c9e-ac445c313d38\",\"webcompat@mozilla.org\":\"4990308d-949f-4e11-8518-2005ce3d631b\",\"default-theme@mozilla.org\":\"ed558a0b-32f4-42c4-9d61-65ab08f5bb3d\",\"google@search.mozilla.org\":\"6b60fe98-7d90-4238-990d-44805a4acc29\",\"bing@search.mozilla.org\":\"dc22a669-f451-4d82-af9e-e78545a782c5\",\"ddg@search.mozilla.org\":\"1fb2b203-589e-483e-aa1d-fe32be6d8b44\",\"mercadolivre@search.mozilla.org\":\"d9564f97-c143-4d9e-a601-90e587835364\",\"twitter@search.mozilla.org\":\"d7895931-454d-4854-8b04-d423e4707664\",\"wikipedia@search.mozilla.org\":\"3b50afb4-cd69-4098-8e63-6db2a993d8fc\",\"{f18f0257-10ad-4ff7-b51e-6895edeccfc8}\":\"df5b083d-ad28-4051-8fa3-300f678a4cbf\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.eme.enabled", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a29c25d4-608e-4677-9fd2-8561fb069957");
user_pref("security.sandbox.plugin.tempDirSuffix", "b75d27cd-d064-4072-b632-0d3baf094601");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1585246966);
user_pref("toolkit.telemetry.cachedClientID", "d50826ad-d10c-4235-ab02-d3f2068f7b16");
user_pref("toolkit.telemetry.previousBuildID", "20200309095159");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
